# Generated by Django 4.1 on 2022-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('prise_day', models.FloatField()),
                ('prise_dayafter', models.FloatField()),
                ('prise_week', models.FloatField()),
                ('prise_monthe', models.FloatField()),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
        ),
    ]
